# Generated by Django 5.1.2 on 2026-08-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_datos_iniciales_especialidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='2 de Agosto & Av. 13 de Diciembre, Valencia, Ecuador', max_length=300)),
                ('telefono_1', models.CharField(default='0994385607', max_length=20)),
                ('telefono_2', models.CharField(blank=True, default='0989895673', max_length=20)),
                ('email', models.EmailField(default='zumedical20@gmail.com', max_length=254)),
                ('horario_lunes_viernes', models.CharField(default='8:30 - 17:00', max_length=100)),
                ('horario_sabados', models.CharField(default='9:00 - 15:00', max_length=100)),
                ('horario_domingos', models.CharField(default='9:00 - 15:00', max_length=100)),
                ('emergencias_24h', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Información de Contacto',
            },
        ),
    ]
