# Generated by Django 5.1.2 on 2026-07-27 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_paciente_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_embarazo',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='NINGUNO', help_text='Indica si la paciente tiene un embarazo en curso', max_length=20, verbose_name='Estado del Embarazo Actual'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medico_prenatal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_prenatales', to=settings.AUTH_USER_MODEL, verbose_name='Médico prenatal responsable (actual)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='mensaje_prenatal_visto',
            field=models.BooleanField(default=False, verbose_name='Mensaje Prenatal Visto'),
        ),
        migrations.CreateModel(
            name='Embarazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha cuando se activa el seguimiento prenatal', verbose_name='Fecha de Inicio del Embarazo')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Parto')),
                ('semanas_gestacion_inicio', models.IntegerField(default=0, verbose_name='Semanas de Gestación al Inicio')),
                ('semanas_gestacion_fin', models.IntegerField(blank=True, null=True, verbose_name='Semanas de Gestación al Parto')),
                ('estado', models.CharField(choices=[('Activo', 'Embarazo Activo'), ('Finalizado', 'Embarazo Finalizado'), ('Suspendido', 'Embarazo Suspendido')], default='Activo', max_length=15, verbose_name='Estado del Embarazo')),
                ('tipo_parto', models.CharField(blank=True, choices=[('normal', 'Parto Normal'), ('cesarea', 'Cesárea'), ('induccion', 'Inducción'), ('otro', 'Otro')], max_length=15, null=True, verbose_name='Tipo de Parto')),
                ('observaciones_parto', models.TextField(blank=True, default='', verbose_name='Observaciones del Parto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medico_prenatal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarazos_dirigidos', to=settings.AUTH_USER_MODEL, verbose_name='Médico prenatal responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Embarazo',
                'verbose_name_plural': 'Embarazos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
