# Generated by Django 5.1.2 on 2026-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_general', '0002_consultageneral_proxima_cita_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultageneral',
            name='conclusion_diagnostica',
            field=models.TextField(blank=True, default='', verbose_name='Conclusión diagnóstica'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='diagnostico_clinico',
            field=models.TextField(blank=True, default='', verbose_name='Diagnóstico clínico'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='especialidad',
            field=models.CharField(choices=[('medicina_general', 'Medicina General'), ('odontologia', 'Odontología'), ('ecografia', 'Ecografía Diagnóstica')], default='medicina_general', max_length=20, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='hallazgos',
            field=models.TextField(blank=True, default='', verbose_name='Hallazgos'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='medicamentos_recetados',
            field=models.TextField(blank=True, default='', verbose_name='Medicamentos recetados'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='odontograma',
            field=models.TextField(blank=True, default='', verbose_name='Odontograma / Observaciones dentales'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='piezas_dentales_tratadas',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Piezas dentales tratadas'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='procedimiento_realizado',
            field=models.TextField(blank=True, default='', verbose_name='Procedimiento o tratamiento realizado'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='recomendaciones',
            field=models.TextField(blank=True, default='', verbose_name='Indicaciones / Recomendaciones'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='region_examinada',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Región anatómica examinada'),
        ),
        migrations.AddField(
            model_name='consultageneral',
            name='tipo_ecografia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de ecografía'),
        ),
        migrations.AlterField(
            model_name='consultageneral',
            name='examen_fisico',
            field=models.TextField(blank=True, default='', verbose_name='Examen físico / Observaciones clínicas'),
        ),
        migrations.AlterField(
            model_name='consultageneral',
            name='examenes_enviados',
            field=models.TextField(blank=True, default='', verbose_name='Exámenes solicitados'),
        ),
    ]
